//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterApp3Entities : DbContext
    {
        public MasterApp3Entities()
            : base("name=MasterApp3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IdentifikacioniDokument> IdentifikacioniDokument { get; set; }
        public DbSet<Mesto> Mesto { get; set; }
        public DbSet<Osoba> Osoba { get; set; }
    }
}
