//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentifikacioniDokument
    {
        public IdentifikacioniDokument()
        {
            this.Osoba = new HashSet<Osoba>();
        }
    
        public long Id { get; set; }
        public string Naziv { get; set; }
        public string BrojIdentifikacionogDokumenta { get; set; }
        public Nullable<long> MestoIzdavanjaId { get; set; }
        public Nullable<System.DateTime> VaziDo { get; set; }
        public Nullable<System.DateTime> VaziOd { get; set; }
    
        public virtual Mesto Mesto { get; set; }
        public virtual ICollection<Osoba> Osoba { get; set; }
    }
}
