//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PravnoLice : Osoba
    {
        public long Id { get; set; }
        public string PunoIme { get; set; }
        public Nullable<System.DateTime> DatumOsnivanja { get; set; }
        public string PIB { get; set; }
    
        public virtual Osoba Osoba { get; set; }
    }
}
